name: update-image-daily
on:
  schedule:
    - cron:  '0 8 * * *'   # 08:00 UTC  →  00:00 Pacific Standard Time
    - cron:  '0 7 * * *'   # 07:00 UTC  →  00:00 Pacific Daylight Time
  workflow_dispatch:   # allows manual runs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install openai requests --quiet
      - run: python generate.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      - name: Commit & push if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [[ `git status --porcelain` ]]; then
            git add daily.png daily.json
            git commit -m "chore: daily image $(date -u +"%F")"
            git push
          else
            echo "No changes, nothing to commit."
          fi
