name: update-image-daily

permissions:          # <-- add this block
  contents: write

on:
  schedule:
    - cron:  '0 8 * * *'   # 00:00 PST
    - cron:  '0 7 * * *'   # 00:00 PDT
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install openai requests --quiet
      - name: Run generator
        run: |
          python generate.py
          echo "---- git status after generate ----"
          git status -s
          ls -l daily.png daily.txt daily.json || true
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Commit & push if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [[ `git status --porcelain` ]]; then
            git add 83afab3c39.png 83afab3c39.json 83afab3c39.txt
            git commit -m "chore: daily image $(date -u +"%F")"
            git push
          else
            echo "No changes, nothing to commit."
          fi
