name: update-image-daily

permissions:
  contents: write          # ← essential for push

on:
  schedule:
    - cron:  '0 8 * * *'   # 00:00 PST
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install --quiet openai requests pillow

      - name: Run generator
        run: python -u generate.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Show post-generate status   # DEBUG – keep until it works
        run: |
          echo "CWD: $(pwd)"
          ls -l 83afab3c39.* || true
          git status -s

      - name: Commit & push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add -A
          git diff --cached --quiet && echo "No changes" && exit 0

          git commit -m "chore: daily image $(date -u +'%F')"
          git push
